### ISSUE TITLE
Client crash when putting Redwood planks in Tinkers crafting table to make a door

### ISSUE THREAD

**Issue by archonsd** [TheCodex6824/ThaumicAugmentation#48] opened 2019-10-24 14:41 UTC
Pastebin: https://pastebin.com/X57RAHFB

Forge 2847
MC 1.12
ThaumicAugmentation-1.12.2-1.1.10.jar

**Comment by archonsd** [comment] 2019-10-24 14:47
I remembered the cause a bit better and updated the subject.

I pasted the error log here because it appears the error was in a Thaumic Aug call..

**Comment by TheCodex6824** [comment] 2019-10-24 19:27
This specific crash seems to be caused by Optifine creating a chunk with a null world, which is really not supposed to be null. In this case it's easy enough to guard against on my end, but I can't always guarantee compatibility with every crazy thing Optifine tries to do.

**Comment by archonsd** [comment] 2019-10-24 19:56
Thanks. I thought Optifine, being client side only, was only a graphics tweak. Does it actually 'create chunks,' per se?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by archonsd** [comment] 2019-10-24 19:58
I should ask, is it something that should be reported to Optifine?  And is it something you'll be releasing a patch to guard against?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by TheCodex6824** [comment] 2019-10-24 20:08
If you take a look at the crash report you sent me, while my mod is at the very top, a few lines down is Optifine code (something to do with shaders?). I used that to do some investigation to find out it was indeed Optifine's fault. I didn't read too far into it, but it's creating a chunk instance to pass into something. I'm working on something right now, and after I test it I'll be releasing an update that should fix this issue.
As for reporting it to Optifine, you can if you want - that world field is not marked as being Nullable in the event so I still don't think this was my fault, but maybe I was just being a bit too idealistic in my assumptions that these things wouldn't happen.

**Closed** 2019-10-24 20:23 UTC
Labels: Compatibility

**Comment by TheCodex6824** [comment] 2019-10-24 20:29
The update should be available [here](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/2815786).

**Comment by archonsd** [comment] 2019-10-24 22:53
Thank you sir.
