### ISSUE TITLE
Crashing when walking thru dimensional fracture

### ISSUE THREAD

**Issue by That1Clarinet** [TheCodex6824/ThaumicAugmentation#29] opened 2019-08-11 20:33 UTC
My server crashed instantly when someone walks thru a fracture i dont know how to read crash info so im hoping someone here does...
[crash-2019-08-11_15.27.00-server.txt](https://github.com/TheCodex6824/ThaumicAugmentation/files/3490413/crash-2019-08-11_15.27.00-server.txt)

**Comment by TheCodex6824** [comment] 2019-08-11 21:23
So I *think* this was caused by the biome block generation around fractures not liking OpenTerrainGenerator, give the update [here](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/2759997) a try.

**Comment by That1Clarinet** [comment] 2019-08-11 21:43
this looks like its done it ill knock it around a bit but im not insta crashing as i go through. Side note: The fracture that you opened to get there is closed on the other side. Thanks a'buchems!

**Comment by TheCodex6824** [comment] 2019-08-11 21:46
Glad it's working for you, and the fracture being closed is probably because the game crashed before it got to the opening part. I'm going to close this since it seems like I was right with what the problem was, but if it crashes again leave a comment here and I'll reopen it.

**Closed by TheCodex6824** 2019-08-11 21:46 UTC
Labels: Bug, Compatibility
