### ISSUE TITLE
Void Caster Gauntlet Crashed Game

### ISSUE THREAD

**Issue by neur0breed** [TheCodex6824/ThaumicAugmentation#6] opened 2019-05-03 02:12 UTC
When I tried to attach a Greater Focus to my 'new' Void gauntlet the game instantly crashed, since then I can't even rejoin the server as "The game crashed whilst unexpected error
Error: java.lang.ClassCastException: thaumcraft.api.casters.FocusPackage cannot be cast to thaumcraft.api.items.IArchitect" error repeatedly crashes the game
[crash-2019-05-02_22.11.07-client.txt](https://github.com/TheCodex6824/ThaumicAugmentation/files/3140475/crash-2019-05-02_22.11.07-client.txt)

**Comment by TheCodex6824** [comment] 2019-05-03 03:51
You appear to be running an old version, this was fixed in the version after yours. Updating will stop the crashes.

Closing as duplicate of #4.

**Closed by TheCodex6824** 2019-05-03 03:51 UTC
Labels: Duplicate
