### ISSUE TITLE
Suggestions and Feedback

### ISSUE THREAD

**Issue by TechnoMysterio** [TheCodex6824/ThaumicAugmentation#3] opened 2019-04-19 23:54 UTC
After some testing with this addon to see what it has to offer, I've come up with some thoughts and suggestions. This addon is good, but these tweaks could really help improve it:

- Light Focus Effect's limited duration. This seems odd. Thaumcraft already has a means of creating intangible lights (outside of Nitor) with the Lamplighter infusion enchantment for pickaxes, axes and shovels, which allows you to place invisible lights when you break blocks in dark underground areas, and these lights are permanent. Perhaps make it so that the Light Focus effect's lights are permanent so to better match the Lamplighter enchant, but to make this fairer perhaps you need to have infusion enchantments page unlocked before you can research the Light effect.
- Light Focus Effect in the Focal Manipulator. Specifying the duration in the Focal Manipulator is very annoying since it increments in seconds and doesn't seem to stop. For example, if you have a greator focus, set the medium to be a bolt and then choose light, you can click the duration increase button 129 times before you max it out. If you decide to keep the limited duration, perhaps make it increment in minutes, starting at one and going up to ten perhaps.
- Light Effect Complexity. The light spell gets very high values of complexity and Vis costs very quickly, which is strange considering how simple the effect is. The greater focus bolt light spell I described earlier costs 510 Vis to create and uses 10 Vis per cast, which seems like way too much. I'd suggest cutting down the general Vis costs of this spell a little.
- The Light Focus effect's light block is a little dull, just being a tiny glowing cube. I'd recommend making it look more like Nitor, but more of a glowing orb than a magical flame.
- Crafting the Void Gauntlet. This is annoying because you place the Thaumium Gauntlet at the centre of the infusion, and as such you can't start the infusion with it because it's on the centre pedestal. If possible, perhaps make the infusion automatically start upon placing the gauntlet at the centre, as long as all the other ingredients are in place first. If you do this, make sure to mention it clearly in the book.
- Small note about the warded chest: it doesn't show up in creative mode search for some reason. Not a big problem, just something strange I noticed.
- The Vis Regenerator animation could be improved a little. Perhaps it could gradually slow down as the Vis in the aura starts to fill up and slowly wind up when it activates itself. Just a minor tweak. The particle effect could be a little better too, the bonemeal effect is a little dull. I know Thaumcraft has a lot of particle effects built into it, like ones for Flux or Salis Mundis creation, so maybe recycle/remix those if you can. Mechanically the Regenerator seems good, it could just do with some fancying up.
- The art generally in the mod is a little lacking. Some of the sprites are fine, like the warding sigil, but a lot of it could do with improving. Things like the two Gauntlets, the Vis Regenerator or the doors. Unfortunately I'm not much of an artist, so while I know they could be improved I don't really know how.

Well aside from my endless list of things that are probably fine and I'm just nitpicking, I do think this addon is pretty good. The Seal Copier is brilliant and the Gauntlets are also very good, even if the art could be improved. I actually came up with my own idea for a Thaumcraft addon that added a Void Metal and Thaumium Gauntlet some time ago, so clearly you stole this idea from me using your incredible psychic powers. Truly devious.

While I'm here, I should probably invite you to the Thaumcraft addon Discord, where a bunch of other Thaumcraft addon devs have gathered. It's a good place to discuss making TC addons, so if you need help with anything like artwork, feel free to ask there: https://discord.gg/bBsBJWW

**Comment by TheCodex6824** [comment] 2019-04-20 01:00
First of all, thank you very much for the detailed feedback! I'm glad you (overall) think this mod is good. As for the points you bring up:

- I gave the light effect a limited duration because I didn't want it to replace the infusions, but having it on the tool is probably convenient enough over having to cast something, so having it with infinite duration would be fine.
- The duration annoyance happens because I set a very wide range for the allowed duration (10 - 180 seconds I think?) when it probably should have been more like 120 - 180 at least. Since I'm probably going to remove the duration, that won't be a problem anymore. 
- I agree with the cost being too high, I think I need to reduce the scaling on the complexity based on light intensity (it gets multiplied by 1.5 for complexity currently, keeping it * 1 or maybe even * 0.75 would be better)
- I'm not really happy with how the light block looks either, an orb with some particles around it sounds much better.
- I didn't even notice the gauntlet thing because I always kept the original one on me for testing things. I'll have to think about how to handle that, as I don't want to start it automatically (even with warning) in case people need to bring essentia jars or something up to it, given how it is a somewhat unstable infusion.
- The chest being missing was caused by me being stupid with the creative tab stuff, that fix should be pushed soon.
- I can fix the vis regenerator to have a gradual animation instead of just stopping and starting, I just got kinda lazy with that.
- All the art was made by me, and I know more than anyone that I'm absolutely terrible at art. If I can get someone that is good at that stuff to help things would look so much better.

 I probably will be joining that discord soon, I didn't know there was one for Thaumcraft addons. Thank you again for writing out a big list of improvements for me.

**Comment by TechnoMysterio** [comment] 2019-04-20 12:21
Great to hear that you're looking to continue working on this addon. There's some great stuff here, it just needs a little polishing mainly. Some further thoughts of mine:

- The addon's tab in the Thaumonomicon could do with a little improving:
- Firstly, and this is mostly me being pedantic, but the name of the tab might work better as just 'Augmentation', since all the other tabs are just one word, and having the word 'Thaumic' in the Thaumonomicon seems redundant.
- Secondly, the tab could do with a better icon. I understand your plight with knowing that you're bad at art but being unable to do better, but an interesting thing about a lot of the textures in base Thaumcraft is that Azanor just pinched stuff off of different art sites. I know that the aspect icons are all from game-icons.net, and that one of the research icons for earlier versions of the mod was taken from a Deviantart image, with the author of said post even complaining that someone called 'Azanor' used their artwork in a mod called Thaumcraft. It's as amusing as it is enlightening. As such, I'd have a ponder as to what kind of icon might suit your addon best (what's the addon about? What would best describe it in a single image?), and maybe peruse Google images for a while, making sure that if you use one of those images then that the license for it allows you to use it in your addon's book tab and perhaps the Curseforge page. Or just nick it anyway, Azanor doesn't seem to care much about these things, certainly.
- Regarding the Gauntlets' art, one thing that doesn't work too good is the fact that they can be coloured, and this colour is a little at odds with the Void Metal/Thaumium parts of the Gauntlets' textures. Another artistic suggestion I might make to you is to have a look at the Void Thaumaturge Robes' texture files and, uh, 'take inspiration' from them, since they can be coloured in a similar manner.

I noticed your name pop up on the Discord, so do go ahead and introduce yourself, you can be added to the list of addon devs on the server then. Anyway, keep up the good work, and with any luck you may be able to get some help with the artwork for the mod.

**Comment by slowiu06** [comment] 2019-05-05 10:48
You did a really good work. Everything suits Thaumcraft style and works pretty well. Something like Casuality Collapser but in form of Focus would be amazing too.

**Comment by TheCodex6824** [comment] 2019-05-08 01:29
> You did a really good work. Everything suits Thaumcraft style and works pretty well. Something like Casuality Collapser but in form of Focus would be amazing too.

I'm glad you like the mod. As for a causality collapser focus, I feel like that would be a bit unbalanced as those are expensive to make. If your main concern is that primordial pearls are a bit too grindy to get, we agree, and are discussing some ways to help remedy that.

Anyway, seeing as 99.99% of the points brought up originally were addressed (with only some animation tweaking to do in the future), I'm going to go ahead and close this. Of course, feedback and suggestions are always appreciated, so anyone can feel free to open up another issue if they have any.

**Closed by TheCodex6824** 2019-05-08 01:29 UTC
Labels: Enhancement
