### ISSUE TITLE
TA apparently interfering ALL collision events, creating huge amounts of lag on servers

### ISSUE THREAD

**Issue by aaronhowser1** [TheCodex6824/ThaumicAugmentation#109] opened 2020-10-22 15:57 UTC
FTBTeam/FTB-University/issues/51

![](https://user-images.githubusercontent.com/15698722/96898116-f844d100-1454-11eb-899a-f0f7728fa70d.png)

FTB University has Thaumic Augmentation, which is apparently causing a gigantic amount of lag on servers. I assume the server owner ran a profiler or something similar to see what was causing the lag, and it was Thaumic Augmentations. Removing it fixed the problem.

I really want to keep this mod in Uni, but unfortunately with the lag it was causing, it has to be removed if it isn't fixed.

**Comment by TheCodex6824** [comment] 2020-10-22 16:04
I'm currently in class but one it's done I'll fix it ASAP. Apparently I need to run more mods in my test packs, because I didn't notice anything wrong in testing, but I can see where it can turn into a massive problem.

**Comment by aaronhowser1** [comment] 2020-10-22 16:39
It's fine in single player, as far as I've seen. Though on that server, it was chugging down to 6 tps and lower, with less than 10 people with early-game bases.

**Comment by TheCodex6824** [comment] 2020-10-22 17:33
Update [here](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation/files/3089750) should fix the lag once it gets approved, let me know if there's any other issues.

**Comment by DoomRater** [comment] 2020-10-23 23:08
I may do triage of my own modpack to see if this drops some of the constantly growing packets when in the base area.  There are Malisis Doors and Mannequin entities abound and eventually the modpack starts needing more data transfer than my poor 10Mbit connection can handle forcing a restart.  I want to see if this update deals with it.

**Comment by TheCodex6824** [comment] 2020-10-24 00:43
Unfortunately I don't think this will fix your connection issues (or that they come from my mod at all, for that matter). The original issue was caused by me using the collision box event for something (because there was no other non-coremod way to selectively collide with certain entities, but let others through), but in that pack it gets called hundreds of thousands of times by something, so it blocked the game thread by the sheer amount of events getting pushed. This mod doesn't really do too much major networking either, especially not when you're not using / holding any mod content. The only thing I can think of that transfers semi-frequently is the ward data on chunk load, but in 99% of cases it's just a few bytes saying "there's nothing here". Of course, the problem could be that the network thread was getting starved for CPU time by the massive lag, in which case this might help.

As always, if I'm wrong and it turns out to be my fault (again...) then let me know.

**Comment by DoomRater** [comment] 2020-10-24 16:46
I haven't been able to benchmark over multiple days but it does seem like my bandwidth usage isn't growing out of control doing things that used to do it, like jumping back and forth between multiple Astral Sorcery gates, running the ore processing plant, and so on.  I also haven't seen any messages about MalisisCore leaking memory either.  But my testing windows are limited because the adults of the house stream videos and when they do I can't even stay connected, update or not.

**Comment by TheCodex6824** [comment] 2020-11-02 17:19
It seems like the issue over on their end was closed so I'm going to close this as well, but if the lag is still an issue someone can leave a comment here and I'll take another look.

**Closed by TheCodex6824** 2020-11-02 17:19 UTC
Labels: ASAP, Bug, Compatibility, Waiting for Confirmation
