### ISSUE TITLE
[Bug] Warded Chest open animation is slower than the vanilla or hungry chest

### ISSUE THREAD

**Issue by Turkey9002** [TheCodex6824/ThaumicAugmentation#229] opened 2021-08-09 22:27 UTC
The animation when opening a warded chest is a lot slower for some reason. Sometimes the model would flash as well when opened a bunch of times. I made sure this was tested without any third party mods as well.

**Comment by Vapaman** [comment] 2021-08-09 23:04
I think it is intended, it being warded and made from heavy thaumium and all. But the animation is still a bit janky; if the opening animation is interrupted it snaps fully open quickly to perform the closing animation. It is noticable when comparing to regural chests.

**Comment by TheCodex6824** [comment] 2021-08-09 23:25
Pretty much all of the model-based animations are like that and need to be fixed. Last time I tried to fix them I ran into some odd issues, but maybe I'll be able to figure out what was going wrong that time.

**Comment by Vapaman** [comment] 2021-08-09 23:27
Wasn't there problems with the impetus stuff too and fixing them would mean you have basically redo them altogether? Is there a similiar issue with other model-based animations?

**Comment by TheCodex6824** [comment] 2021-08-09 23:40
Pretty much the problem is that I am currently using the [Forge Animation System](https://mcforge.readthedocs.io/en/1.12.x/animation/intro/) for some block model animations, and either I'm being stupid or there is an issue where the animation sometimes repeats the first frame the animation at the end of the cycle. Getting "sudden transitions" (quickly opening and closing the chests for example) right also seem to elude me at the moment.

I probably just need to reread the docs carefully and try again. This mod also seems to be the only one that uses these (other than example mods), so I can't check anything else for help.

**Comment by TheCodex6824** [comment] 2021-08-13 23:39
I made the animation much more consistent - it should no longer flicker, and will correctly cycle animations if it is opened and closed really quickly. The speed I will keep the same for now as it is heavy, being made of metal and all.

**Closed** 2021-08-14 15:39 UTC
Labels: Bug, Enhancement, Fixed in Dev
