### ISSUE TITLE
[Suggestion] Configurable impetus (and potentially vis?) generator values

### ISSUE THREAD

**Issue by l4ssc** [TheCodex6824/ThaumicAugmentation#219] opened 2021-07-28 15:08 UTC
I'm making a modpack and I'd love to make the methods that Thaumcraft and TA provide for generating FE work better with the power consumption and production levels of other machines in the pack. However, it seems like both mods have not added the ability to change the total amount of FE per vis/impetus nor the FE/t output of the machines in their respective configuration files (unless I'm blind). Obviously, given that this repo is for an addon and not the main mod I would understand just changing this for just the impetus generator but given that Azanor is AWOL currently I'd figure I'd ask for both anyway. This would just be a nice change to fit the machines into the power ecosystem of any given pack :)

**Comment by TheCodex6824** [comment] 2021-07-29 22:37
I'll definitely add config options for the things this mod adds like the Impetus Generator. The Vis Generator would require major alterations to support changing the power generation parameters so I probably won't be doing that, sorry. I don't think redoing the Vis Generator is expected behavior from a content addon like this one.

Also I just took a peek at the Impetus Generator code as a refresher and it looks like right now it might inadvertently be able to be used as a battery in some situations. It can only store 3000 FE at the moment, but that isn't intended behavior so I should probably remove that. Would that cause problems for you?

**Comment by DoomRater** [comment] 2021-07-29 23:22
Huh, I just probed it with Industrial Renewal's Energy Level indicator and it only reads an internal battery when hooked directly up to the output.  I would have thought it didn't have one at all if I hadn't read this report.

**Comment by TheCodex6824** [comment] 2021-07-30 03:10
Yep, the energy is only exposed on the output side. I inadvertently advertised the generator as being able to receive energy out of that side in addition to sending it, but that should be fixed now. As for the config stuff, I added options for buffer size, FE per impetus, and extraction rate. Hopefully that helps you!

I also realize I should probably do the same thing for the stability field generator (and eventually all of the impetus machines as well), but it's getting a bit late here so that sounds like something for another day.

**Comment by l4ssc** [comment] 2021-07-31 10:11
First off, thank you so much for implementing it in such a timely manner! <3

> I probably should have asked this question earlier: is there a specific reason why you want to tweak these values? Obviously I'm going to let people do what they want, but I haven't heard much feedback on whether the Impetus Generator is worthwhile or not beyond just running a few stability field generators.

Personally, I think the default values for the generators are actually pretty good! 50 FE/t seems small until you realize just how much impetus a decently large rift makes and how many generators can run off of one.

From the perspective of the modpack however, it's the idea of having unconventional sources of energy produce much more power than the typically used options to incentivize the player to learn about and use vastly different methods of generation (as what I'm making is going to be an expert-mode pack) that drives the design, so I'm basically trying to change the values of _all_ power sources and consumers to balance them around that. 

As for the vis generator, no worries there- maybe I'll try my hand at it in a separate project!

**Comment by TheCodex6824** [comment] 2021-08-01 02:21
> As for the vis generator, no worries there- maybe I'll try my hand at it in a separate project!

Yeah sorry about that, in general I don't like adding general fixes here because then people would be forced to use the mod even if they don't want the content, which I don't want to do. However, [ThaumTweaks](https://www.curseforge.com/minecraft/mc-mods/thaumtweaks) would probably be a good place for that kind of change, so you might be able to ask the author of that mod if they would consider adding it.

If you do try adding it yourself, writing a mixin would probably be the easiest way, but make sure to use the latest version for 1.12 - otherwise, it might crash when ran alongside other mods that *do* ship a newer mixin.

**Comment by Vapaman** [comment] 2021-08-02 00:50
In my opinion this addon is so good that peeps that play TC6 should be forced to try Augmentation :P

**Closed** 2021-08-14 15:39 UTC
Labels: Enhancement, Fixed in Dev
