### ISSUE TITLE
Void Thaumaturge set brought in Vis

### ISSUE THREAD

**Issue by BlueHNT** [TheCodex6824/ThaumicAugmentation#320] opened 2022-10-24 15:37 UTC
I was just doing my own thing using the void thaumaturge 3 pieces set together with the "Amulet of Vis" and it caused an insane amount of vis pollution everywhere, setting all the vis to 33.6k to the limit of possible vis in chunks. It is causing me a lot of rifts and taint due to it and there is no way to get rid of all that vis since a whole 16x16 area is contaminated with hundreds of thousands of vis.

I don't know how replicable it is, but all I need to repeat the issue.
Wear a void thaumaturge set that is fully charged together with the Amulet of Vis.

That's all... I'm serious.

Here's some pics to serve proof to the issue.
![1](https://user-images.githubusercontent.com/79374236/197566905-b146bc04-1fce-42bb-95d3-abed22ae06da.png)
![2](https://user-images.githubusercontent.com/79374236/197566961-7e2037be-6bee-48cd-b673-175ad225968a.png)

**Comment by TheCodex6824** [comment] 2022-10-24 16:23
A few questions:

1. Does this happen without Thaumic Augmentation installed? Both the *Void* Thaumaturge Armor and the Amulet of Vis are base Thaumcraft items, so it might not be this mod causing it.
2. Being able to charge the Void Thaumaturge Armor with vis is not in base Thaumcraft - I think ThaumTweaks adds that. Does this still happen without ThaumTweaks?

Regardless of what might be causing it, if you have operator / cheats enabled, try using `/ta fixaura` while standing in the affected area (forcing it if needed). That should reset the area to normal values.

**Comment by BlueHNT** [comment] 2022-10-26 23:28
I am talking about the thaumaturge armor added **BY** the mod directly and is not affected by any other means. It is possible it might be due to the thaumtweaks but I am unsure as I do not have time to test that.

Note, it was too late for any backup to be in use at that point so I am kind of forced to clean up chunk vis with vis generators and a load of flux eating stuff...

/ta fixaura I'll try this

**Comment by BlueHNT** [comment] 2022-10-27 12:32
the fixaura did jack shit and I have no clue how to make it "force" the usage of it as it just says "USE THE FORCE OPTION TO REGENERATE ANYWAY" so its fucked

**Comment by BlueHNT** [comment] 2022-10-27 12:35
Nevermind, if only I knew how to skip the chunk X Z and dim so its always the one I'm in so I can just around copy pasting the aura fix, that would be neat

**Comment by BlueHNT** [comment] 2022-10-27 12:36
THIS IS EATING AWAY AT MY SANITY, like holy shit

**Comment by TheCodex6824** [comment] 2022-10-27 18:50
> I am talking about the thaumaturge armor added BY the mod directly and is not affected by any other means. 
Assuming you are talking about the Thaumium Robes (not the Void Robes), those are indeed added by this mod, but should only give a Vis discount, not actually store Vis.

> the fixaura did jack shit and I have no clue how to make it "force" the usage of it as it just says "USE THE FORCE OPTION TO REGENERATE ANYWAY" so its fucked

There is a boolean parameter at the end that sets that. The reason that's there is to prevent issues from people using the command unnecessarily, because the aura regeneration process may not regenerate the 100% exact aura as at world generation time.

> Nevermind, if only I knew how to skip the chunk X Z and dim so its always the one I'm in so I can just around copy pasting the aura fix, that would be neat

You can, although dim always needs to be set (I forget why I made it like that, but I probably had a good reason):
`/ta fixaura ~ ~ 0 true` if in the overworld (dimension 0). Nether is -1, end is 1.

**Comment by BlueHNT** [comment] 2022-10-28 10:18
> > I am talking about the thaumaturge armor added BY the mod directly and is not affected by any other means.
> 
> Assuming you are talking about the Thaumium Robes (not the Void Robes), those are indeed added by this mod, but should only give a Vis discount, not actually store Vis.

It somehow stores the vis, might be affected by thaumtweaks indirectly causing this issue then, it may be worth checking out then.

> > the fixaura did jack shit and I have no clue how to make it "force" the usage of it as it just says "USE THE FORCE OPTION TO REGENERATE ANYWAY" so its fucked
> 
> There is a boolean parameter at the end that sets that. The reason that's there is to prevent issues from people using the command unnecessarily, because the aura regeneration process may not regenerate the 100% exact aura as at world generation time.

I kind of did that manually due to my mid knowledge of mc commands and general structure of mods

> > Nevermind, if only I knew how to skip the chunk X Z and dim so its always the one I'm in so I can just around copy pasting the aura fix, that would be neat
> 
> You can, although dim always needs to be set (I forget why I made it like that, but I probably had a good reason): `/ta fixaura ~ ~ 0 true` if in the overworld (dimension 0). Nether is -1, end is 1.

Thank you, I have uhh... used /ta fixaura ~ ~ ~ true instead and then went 1 by 1 over like 200 chunks fixing them.. It was entirely my fault..

Oh and I should probably mention, this issue arose on the 1.12.2 perfectly complex pack version 1.5.1. so it's not an entirely obsolete issue, but I'll try bringing this up with the thaumtweaks community aswell

**Comment by Krutoy242** [comment] 2023-02-04 08:48
This bug was caused by ThaumTweaks and was fixed in `thaumtweaks-0.3.5.3`
https://github.com/GrigLog/ThaumTweaks/issues/40

**Comment by TheCodex6824** [comment] 2023-03-19 03:07
> This bug was caused by ThaumTweaks and was fixed in `thaumtweaks-0.3.5.3` [GrigLog/ThaumTweaks#40](https://github.com/GrigLog/ThaumTweaks/issues/40)

Thanks!

**Closed by TheCodex6824** 2023-03-19 03:07 UTC
