### ISSUE TITLE
[BUG] Thaumic Augmentation Warded Chest Causes GTCE Chests To Go Transparent.

### ISSUE THREAD

**Issue by DarkAmbientNoise** [TheCodex6824/ThaumicAugmentation#93] opened 2020-09-09 19:49 UTC
Placing a Warded Chest causes any and all GregTech Community Edition Chests to go completely transparent.

Has been reported to GTCE. They feel it's not directly on their end. https://github.com/GregTechCE/GregTech/issues/1235

**Versions**
Forge: 14.23.5.2854
GTCE: 1.12.2-1.10.1.557
CodeChicken Lib 1.8.+: 1.12.2-3.2.3.358-universal
Baubles 1.12-1.5.2
Thaumcraft 1.12.2-6.1.BETA26
Thaumic Augmentation 1.12.2-1.1.19
Modpack: None: Minimum to run GTCE and attempt to catch this bug.
**Addons:**
JEI 1.12.2-4.16.1.301

**Setup**
Playing Solo Super Flat World. New World as a testing environment.

**Steps To Reproduce**

1) Place down one of each of GTCE chests.
2) Place down Thaumic Augmentation's "Warded Chest"
3) Done. Immediate results.

**Expected behavior**
Expect All blocks to still be fully visible.

**Screenshots**
1. Screenshot Immediately after the described steps (Shadows for chests remain)

![2020-09-07_19 51 35](https://user-images.githubusercontent.com/12950685/92422984-f644de00-f144-11ea-9fe6-39d405e96a73.png)

2. Hitboxes and functionality remain.

![2020-09-07_19 58 01](https://user-images.githubusercontent.com/12950685/92423011-0a88db00-f145-11ea-8924-df08dd2271b3.png)
![2020-09-07_19 58 07](https://user-images.githubusercontent.com/12950685/92423013-0c529e80-f145-11ea-9f97-881b07b45333.png)

**Comment by TheCodex6824** [comment] 2020-09-09 21:06
I just did some quick tests, and it seems like GTCE chests are broken by *any* block that uses the Forge animation system (which are pretty much just special FastTESRs). I even uninstalled my mod and all TC stuff, plopped in the Forge debug mod, and saw the exact same thing happen with the animation test blocks. So chances are GTCE (or maybe CCL? I think they use that for some sort of rendering from a quick look at their code, but I didn't dig too deep into that) is the issue here.

That being said, this is a small chance the answer might be that the forge animation system is broken, and if that turns out to be the case then that's a totally new discussion. I doubt that would be it though.

**Comment by DarkAmbientNoise** [comment] 2020-09-09 22:29
Hmm... I am aware that GTCE stuff does have issues with running shaders and tends to throw a lot of CCL render errors. They are aware of this fact however. I don't know much about developing in Minecraft aside from managing to get in a few very simple custom blocks. Thank you for your time and testing though, it's very appreciated! I suppose we'll have to wait and see if they can snatch a solution to whatever is causing this problem.

**Comment by TheCodex6824** [comment] 2020-09-15 19:56
Given that the problem is probably not with my mod, I'm going to close this. If it turns out I'm actually doing something wrong, then I can revisit this.

**Closed by TheCodex6824** 2020-09-15 19:56 UTC
Labels: Can't / Won't Fix, Compatibility
